apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort   # Expose outside cluster
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port
      nodePort: 30007   # External port (must be 30000–32767)
