pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo Building Docker image...'
                sh 'docker build -t my-flask-app:latest ./03-docker'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running container for testing...'
                sh 'docker rm -f test-app || true'
                sh 'docker run -d --name test-app --network jenkins-net -p 5000:5000 my-flask-app:latest'
                sh 'sleep 5'
                sh 'curl http://localhost:5000'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'echo Deploying to Kubernetes...'
                // Delete old deployment if exists
                sh 'kubectl delete -f 04-kubernetes/deployment.yaml || true'
                sh 'kubectl delete -f 04-kubernetes/service.yaml || true'

                // Apply new deployment & service
                sh 'kubectl apply -f 04-kubernetes/deployment.yaml'
                sh 'kubectl apply -f 04-kubernetes/service.yaml'
            }
        }
    }
}
